### ISSUE TITLE
not working when tried in asp.net core 3.0

### ISSUE THREAD

**Issue by PurnaChandraPanda** [jerriep/airport-explorer-source#6]
I think a lot of things have bee changed - from mpaboxgl, google service sides. With current code, not able to run in .NET Core 3.0. May we have some direction here please?

**Comment by jerriep** [comment]
Sorry, I have no intention of updating this for ASP.NET Core 3.x. And as you have mentioned, some of the external services this tutorial depends on has also changed.

You will need to try and figure the upgrade issues for yourself - it will be a good learning experience 😉
